# This file was generated by @liquid-labs/sdlc-projects-workflow-local-node-build.
# Refer to https://npmjs.com/package/@liquid-labs/sdlc-projects-workflow-local-
# node-build for further details

#####
# build dist/command-line-documentation-exec.js
#####

SDLC_COMMAND_LINE_DOCUMENTATION_EXEC_JS:=$(DIST)/command-line-documentation-exec.js
SDLC_COMMAND_LINE_DOCUMENTATION_EXEC_JS_ENTRY=$(SRC)/cli/index.mjs
BUILD_TARGETS+=$(SDLC_COMMAND_LINE_DOCUMENTATION_EXEC_JS)

$(SDLC_COMMAND_LINE_DOCUMENTATION_EXEC_JS): package.json $(SDLC_ALL_NON_TEST_JS_FILES_SRC)
	JS_BUILD_TARGET=$(SDLC_COMMAND_LINE_DOCUMENTATION_EXEC_JS_ENTRY) \
	  JS_OUT=$@ \
	  JS_OUT_PREAMBLE='#!/usr/bin/env -S node --enable-source-maps' \
	  $(SDLC_ROLLUP) --config $(SDLC_ROLLUP_CONFIG)
	chmod a+x $@

#####
# end dist/command-line-documentation-exec.js
#####
